dbt_anp_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_PG_HOST') }}"
      user: "{{ env_var('DBT_PG_USER') }}"
      password: "{{ env_var('DBT_PG_PASSWORD') }}"
      port: "{{ env_var('DBT_PG_PORT') | int }}"
      dbname: "{{ env_var('DBT_PG_DBNAME') }}"
      schema: public
      threads: 4